# THIS IS A PYTHON UTILITY TO PERFORM EDA ON SALES DATA :

In [72]:
import pandas as pd
import seaborn as sns
import matplotlib as plt

## EDA Project : Sales_data

Perform exploratory Analysis on the datasate.

In [73]:
sales_dataset = pd.read_excel(r"C:\Users\USER\Documents\Pythonprac\Sales_project\dirty_supplement_sales_data_2020.xlsx")

In [74]:
sales_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 3100 entries, 0 to 3099
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              3100 non-null   str
 1   Product Category  3100 non-null   str
 2   Product Name      3100 non-null   str
 3   Units Sold        1551 non-null   float64
 4   Units Returned    2495 non-null   float64
 5   Price             2457 non-null   object
 6   Discount (%)      2651 non-null   float64
 7   Revenue           2457 non-null   float64
 8   Platform          3100 non-null   str
 9   Location          3100 non-null   str
dtypes: float64(4), object(1), str(5)
memory usage: 242.3+ KB

In [75]:
print(f"This is the first 5 rows :{display(sales_dataset.head())}")
print(f"This is the Last 5 rows :{display(sales_dataset.tail())}")

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
0,2020-10-07,Sleep Aids,ImmunoPro,NaN,1.0,$10.99,105.0,0.000,Instore,Los Angeles
1,2020-09-16,Vitamins,MuscleMax,NaN,-1.0,NaN,0.0,NaN,Mob App,Houston
2,2020-11-11,Immunity Boosters,Slim F@st,15.0,-1.0,15,NaN,225.000,Online,Chicago
3,2020-11-04,Energy Drinks,PowerFuel,14.0,0.0,$10.99,25.0,115.395,Online,new york
4,2020-06-03,Vitamins,SuperV!ta,NaN,NaN,$10.99,50.0,0.000,Mobile App,new york

This is the first 5 rows :None

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
3095,2020-09-16,Immunity Boosters,SuperV!ta,10.0,2.0,NaN,25.0,NaN,In-Store,Chicago
3096,2020-08-12,Vitamins,DreamRest,25.0,0.0,NaN,25.0,NaN,onlien,New York
3097,2020-10-21,Immunity Boosters,SuperV!ta,NaN,-1.0,$10.99,25.0,0.0,Mobile App,Chi-Town
3098,2020-02-19,Weight Loss,SuperVita,NaN,NaN,NaN,NaN,NaN,Instore,Chicago
3099,2020-08-26,Protein,PowerFuel,NaN,0.0,15,0.0,0.0,Mobile App,Phoenix

This is the Last 5 rows :None

In [76]:
columns = sales_dataset.columns.unique()
print (columns)

Index(['Date', 'Product Category', 'Product Name', 'Units Sold',
       'Units Returned', 'Price', 'Discount (%)', 'Revenue', 'Platform',
       'Location'],
      dtype='str')

In [77]:
sales_dataset.shape # rows and columns

(3100, 10)

In [78]:
# statistical summary numerical features

sales_dataset.describe().T

                 count        mean         std   min   25%   50%    75%    max
Units Sold      1551.0   24.514507   14.398598   1.0  11.5  24.0   37.0   50.0
Units Returned  2495.0    0.478557    1.120023  -1.0  -1.0   0.0    1.0    2.0
Discount (%)    2651.0   35.403621   35.162792   0.0  10.0  25.0   50.0  105.0
Revenue         2457.0  101.290307  159.300390 -37.5   0.0   0.0  180.0  735.0

In [79]:
# Statistical summary for categorical features

sales_dataset.describe(include='str').T

                 count unique         top freq
Date              3100    104  2020-05-20   68
Product Category  3100      6     Protein  555
Product Name      3100      8   Slim F@st  409
Platform          3100      6     Instore  537
Location          3100      8        L.A.  421

In [80]:
# Nulls/ Missing values

sales_dataset.isnull().sum()

Date                   0
Product Category       0
Product Name           0
Units Sold          1549
Units Returned       605
Price                643
Discount (%)         449
Revenue              643
Platform               0
Location               0
dtype: int64

## Data Cleaning :

### Standardize columns :
- This prevents code errors in languages like python if column names contaims hidden spaces, trailing whitespaces and special characters.

-Simplifies merging : Joining datasets ( matching key columns)

_Common Practices in standardization_

- use of lowercase
- replace spaces with underscores
- rename columns

In [81]:
sales_dataset.head()

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
0,2020-10-07,Sleep Aids,ImmunoPro,NaN,1.0,$10.99,105.0,0.000,Instore,Los Angeles
1,2020-09-16,Vitamins,MuscleMax,NaN,-1.0,NaN,0.0,NaN,Mob App,Houston
2,2020-11-11,Immunity Boosters,Slim F@st,15.0,-1.0,15,NaN,225.000,Online,Chicago
3,2020-11-04,Energy Drinks,PowerFuel,14.0,0.0,$10.99,25.0,115.395,Online,new york
4,2020-06-03,Vitamins,SuperV!ta,NaN,NaN,$10.99,50.0,0.000,Mobile App,new york

In [ ]:
# Standardizing the column names
# 1. Stripping any preceding or trailing spaces

sales_dataset.columns = sales_dataset.columns.str.strip()

# 2. Changes the columns to lowercase

sales_dataset.columns = sales_dataset.columns.str.lower()

# 3. Replace empty spaces with underscores 

sales_dataset.columns = sales_dataset.columns.str.replace("","_")

# 4. # Remove % from the discount column and replace with " Percentage"

sales_dataset = sales_dataset.rename(columns=("Discount (%)"))

In [70]:
# Function to standardize columns.

sales_dataset.columns = sales_dataset.columns.str.strip().str.lower().str.replace("","_").str.replace("_(%)","_percentage", regex=False)
# Regex : regular expression( a sequence of special characters that form a serch pattern)

TypeError: Index(...) must be called with a collection of some kind, 'Discount (%)' was passed